# Generated by Django 4.2.4 on 2023-11-14 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dem11app", "0003_otheraids"),
    ]

    operations = [
        migrations.CreateModel(
            name="receiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medcicine", models.CharField(max_length=250)),
                ("quantity", models.PositiveIntegerField()),
                ("disease", models.CharField(max_length=150)),
                (
                    "prescription_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="prescriptions/"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
