# Generated by Django 4.2.4 on 2023-11-14 07:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dem11app", "0004_receiver"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receiver",
            old_name="medcicine",
            new_name="medicine",
        ),
    ]
