# Generated by Django 4.2.4 on 2023-11-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dem11app", "0006_otheraids_current_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otheraids",
            name="current_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/otheraids/"
            ),
        ),
        migrations.AlterField(
            model_name="receiver",
            name="prescription_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/prescriptions/"
            ),
        ),
    ]
