# Generated by Django 4.2.4 on 2023-11-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dem11app", "0010_admins"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name="admins",
        ),
    ]
