# Generated by Django 4.2.4 on 2023-11-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dem11app", "0011_admin_delete_admins"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="email",
            field=models.EmailField(default="admin@gmail.com", max_length=254),
            preserve_default=False,
        ),
    ]
