# Generated by Django 4.2.4 on 2023-11-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dem11app", "0012_admin_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicines",
            name="approved",
            field=models.BooleanField(default="False"),
        ),
        migrations.AddField(
            model_name="medicines",
            name="removed",
            field=models.BooleanField(default="False"),
        ),
        migrations.AddField(
            model_name="otheraids",
            name="approved",
            field=models.BooleanField(default="False"),
        ),
        migrations.AddField(
            model_name="otheraids",
            name="removed",
            field=models.BooleanField(default="False"),
        ),
        migrations.AddField(
            model_name="req_med",
            name="approved",
            field=models.BooleanField(default="False"),
        ),
        migrations.AddField(
            model_name="req_med",
            name="removed",
            field=models.BooleanField(default="False"),
        ),
        migrations.AddField(
            model_name="saving_request",
            name="approved",
            field=models.BooleanField(default="False"),
        ),
        migrations.AddField(
            model_name="saving_request",
            name="removed",
            field=models.BooleanField(default="False"),
        ),
    ]
