# Generated by Django 4.2.4 on 2023-11-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dem11app", "0013_medicines_approved_medicines_removed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("amount", models.FloatField()),
                ("mail", models.EmailField(max_length=254)),
                ("payment_id", models.CharField(max_length=150)),
                ("paid", models.BooleanField(default=False)),
            ],
        ),
    ]
