# Generated by Django 4.2.4 on 2023-11-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dem11app", "0014_payments"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicines",
            name="reached_store",
            field=models.BooleanField(default="False"),
        ),
        migrations.AddField(
            model_name="otheraids",
            name="reached_store",
            field=models.BooleanField(default="False"),
        ),
        migrations.AddField(
            model_name="req_med",
            name="collected",
            field=models.BooleanField(default="False"),
        ),
        migrations.AddField(
            model_name="saving_request",
            name="collected",
            field=models.BooleanField(default="False"),
        ),
    ]
